<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Filament\Models\Contracts\FilamentUser;
use Filament\Panel;

class User extends Authenticatable implements FilamentUser
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    /**
     * Get the orders approved by the user.
     */
    public function approvedOrders()
    {
        return $this->hasMany(Order::class, 'approved_by');
    }

    /**
     * Get the orders rejected by the user.
     */
    public function rejectedOrders()
    {
        return $this->hasMany(Order::class, 'rejected_by');
    }

    /**
     * Get the invoices generated by the user.
     */
    public function generatedInvoices()
    {
        return $this->hasMany(Invoice::class, 'generated_by');
    }

    /**
     * Get the activity logs for the user.
     */
    public function activityLogs()
    {
        return $this->morphMany(ActivityLog::class, 'loggable');
    }

    /**
     * Get the activity logs created by this user.
     */
    public function createdActivityLogs()
    {
        return $this->morphMany(ActivityLog::class, 'user');
    }

    /**
     * Kullanıcının Filament paneline erişip erişemeyeceğini kontrol eder
     */
    public function canAccessPanel(Panel $panel): bool
    {
        // Şimdilik tüm kullanıcılar erişebilir
        // İleride is_admin gibi bir alan eklenebilir
        return true;
    }
}
